package com.example.randomight.engine_logic

object LocalWordBank {
    val words = listOf(
        // A section
        "abandon", "ability", "able", "about", "above", "abroad", "absence", "absent", "absolute",
        "abstract", "abuse", "abusive", "academic", "accede", "accept", "acceptable", "acceptance",
        "access", "accident", "accolade", "accompany", "accomplish", "accord", "according",
        "account", "accountant", "accurate", "accuse", "ache", "achieve", "acknowledge", "acquire",
        "acquit", "acronym", "across", "act", "action", "active", "activity", "actor", "actress",
        "actual", "actually", "ad", "adapt", "add", "addiction", "addition", "additional",
        "address", "adequate", "adjourn", "adjust", "administration", "admiration", "admire",
        "admission", "admit", "adopt", "adoption", "adult", "advance", "advantage", "adventure",
        "adventurous", "advertise", "advertisement", "advice", "advise", "affair", "affect",
        "affection", "affectionate", "afford", "afraid", "after", "afternoon", "again", "against",
        "age", "aged", "agency", "agenda", "agent", "aggravation", "aggressive", "ago", "agree",
        "agreement", "agriculture", "ah", "ahead", "aid", "aim", "air", "air traffic controller",
        "airplane", "airport", "aisle", "alacrity", "alarm", "alcohol", "alert", "alibi", "alimony",
        "alive", "all", "all right", "allergy", "allow", "allowance", "almost", "alone", "along",
        "alphabet", "already", "also", "alter", "alternative", "although", "altogether", "always",
        "amateur", "amaze", "ambiguous", "ambition", "ambitious", "among", "amount", "analogy",
        "analysis", "analyze", "and", "anger", "angle", "angry", "anguish", "animal", "ankle",
        "anniversary", "announce", "annoy", "annoying", "annual", "annually", "another", "answer",
        "antihistamine", "antonym", "anxiety", "anxious", "any", "anybody", "anymore", "anyone",
        "anything", "anyway", "anywhere", "apart", "apartment", "apologize", "apology", "app",
        "apparent", "apparently", "appeal", "appear", "appearance", "appetite", "apple",
        "application", "apply", "appointment", "appreciate", "approach", "appropriate", "approval",
        "approve", "approximate", "April", "aquifer", "arbitrary", "arch", "architect", "area",
        "arena", "argue", "argument", "arm", "armpit", "army", "around", "arrange", "arrangement",
        "arrest", "arrival", "arrive", "arrow", "art", "article", "artificial", "artist",
        "artistic", "as", "ashamed", "aside", "ask", "askance", "asleep", "aspirin", "assess",
        "assignment", "assist", "assistant", "associate", "associate's degree", "assume", "assure",
        "athlete", "athletic", "atmosphere", "attach", "attack", "attempt", "attend", "attention",
        "attitude", "attorney", "attract", "attraction", "attractive", "audience", "augment",
        "August", "aunt", "author", "authority", "automatic", "automobile", "autumn", "available",
        "avarice", "avenue", "average", "avoid", "awake", "award", "aware", "away", "awful",
// B section
        "baby", "bachelor's degree", "back", "backboard", "background", "backhand", "backup",
        "backward", "bacterium", "bad", "badly", "bag", "baggage", "bake", "balance", "balance",
        "ball", "band", "bandage", "bane", "bang", "bank", "banker", "bankrupt", "bankrupt",
        "bankruptcy", "banter", "bar", "barber", "bare", "bark", "barn", "barometer", "barrier",
        "bartender", "base", "baseball", "basic", "basically", "basis", "basket", "basketball",
        "bath", "bathe", "bathroom", "batter", "battery", "battle", "be", "beach", "beak", "bean",
        "bear", "beard", "beat", "beautiful", "beauty", "because", "become", "bed", "bedroom",
        "bee", "beef", "beer", "before", "beg", "begin", "beginning", "behalf", "behave",
        "behavior", "behind", "being", "belie", "belief", "believe", "bell", "belong", "below",
        "belt", "bench", "bend", "beneath", "benefit", "beside", "besides", "best", "bestow", "bet",
        "better", "between", "beyond", "bible", "bibliography", "bicycle", "bid", "big", "bill",
        "billion", "bind", "biodegradable", "biodiversity", "biology", "bird", "birth", "birthday",
        "bit", "bite", "bitter", "black", "blackout", "blade", "blame", "bland", "blank", "blanket",
        "bleed", "blend", "blind", "blizzard", "block", "blog", "blond", "blood", "blow", "blue",
        "board", "boarding pass", "boast", "boat", "body", "boil", "bold", "bomb", "bond", "bone",
        "bone", "bonus", "book", "bookkeeper", "boot", "border", "bore", "boredom", "born",
        "borrow", "boss", "bossy", "both", "bother", "bottle", "bottom", "bounce", "bound",
        "boundary", "bow", "bowl", "box", "boy", "boyfriend", "brace", "brain", "branch", "brand",
        "brave", "bread", "break", "breakfast", "breast", "breath", "breathe", "breed", "breed",
        "breezy", "bribe", "bride", "bridge", "brief", "brief", "bright", "brilliant", "bring",
        "broad", "broadcast", "broken", "bronchitis", "brother", "brother-in-law", "brown",
        "bruise", "brush", "bubble", "bucolic", "budget", "build", "builder", "building",
        "bulkhead", "bullet", "bully", "bulwark", "bunch", "burn", "bury", "bus", "bush",
        "business", "businessman", "businessperson", "businesswoman", "busy", "but", "butcher",
        "butter", "button", "buy", "by", "bye",
// C section
        "cage", "cake", "calculate", "calculation", "calendar", "calf", "call", "callous", "calm",
        "camera", "camp", "campaign", "campus", "can", "cancel", "cancer", "candid", "candidate",
        "candy", "cap", "capable", "capacity", "capital", "captain", "capture", "car", "carbon",
        "carcinogen", "card", "care", "career", "careful", "careless", "carpenter", "carpet",
        "carrot", "carry", "carry-on", "case", "cash", "cashier", "cast", "castle", "cat",
        "catalog", "catch", "catcher", "category", "cattle", "cause", "caution", "cautious", "cave",
        "cease", "ceiling", "celebrate", "celebration", "cell", "cent", "center", "central",
        "century", "ceremony", "certain", "certainly", "certainty", "chain", "chair", "challenge",
        "chamber", "champion", "championship", "chance", "change", "channel", "chaos", "chapter",
        "character", "charge", "charity", "charm", "charming", "chart", "chase", "chat", "cheap",
        "cheat", "check", "cheek", "cheerful", "cheese", "chef", "chemical", "chemistry", "chest",
        "chew", "chicken", "chief", "child", "childhood", "children", "chilly", "chin", "chip",
        "chocolate", "choice", "choke", "choose", "chop", "Christmas", "church", "circle",
        "circumspect", "circumstance", "circumvent", "citation", "citizen", "city", "civil",
        "claim", "clap", "clarify", "class", "classic", "classify", "clause", "clay", "clean",
        "clear", "clerk", "clever", "click", "cliff", "climate", "climb", "clinic", "clock",
        "close", "closet", "cloth", "clothes", "clothing", "cloud", "cloudy", "club", "coach",
        "coal", "coalesce", "coast", "coat", "cockpit", "code", "coffee", "cogent", "coherent",
        "coin", "cold", "cold front", "collapse", "collar", "collect", "collection", "college",
        "color", "column", "comb", "combination", "come", "comedy", "comfort", "comfortable",
        "command", "comment", "commercial", "commission", "commit", "committee", "common",
        "common-law", "communicate", "communication", "community", "community college", "commute",
        "company", "compare", "comparison", "compassion", "compete", "competition", "competitive",
        "complain", "complaint", "complete", "completion", "complex", "complicate", "complicated",
        "component", "compose", "composition", "compost", "compound", "comprehensive", "compulsive",
        "computer", "concentrate", "concentration", "concept", "concern", "concert", "conclude",
        "conclusion", "concrete", "condition", "conduct", "conference", "confidence", "confident",
        "confine", "confirm", "conflict", "confuse", "confusion", "congress", "conjunction",
        "connect", "connection", "conscience", "conscious", "consent", "conservation",
        "conservationist", "conservative", "consider", "considerable", "consideration", "consist",
        "consistent", "constant", "constantly", "constitution", "construct", "construe", "consult",
        "consumer", "consumer goods", "contact", "contagious", "contain", "container",
        "contaminant", "contamination", "contemporary", "content", "contentment", "contest",
        "context", "continent", "continually", "continue", "continuous", "continuously", "contract",
        "contrast", "contribute", "contribution", "control", "convenient", "conversation",
        "convert", "convince", "cook", "cookie", "cool", "cooperate", "cooperation", "cope",
        "copious", "copy", "copyright", "core", "corn", "corner", "corporate", "corporation",
        "corpulent", "correct", "correspond", "cost", "cottage", "cotton", "cough", "council",
        "count", "country", "couple", "courage", "courageous", "course", "court", "cousin",
        "cowardly", "crack", "craft", "crash", "crazy", "cream", "create", "creative", "creature",
        "credence", "credible", "credit", "crew", "crime", "criminal", "crisis", "crisp", "cruel",
        "crutch", "curiosity", "currency", "custody", "customs", "cut", "cynical",
// D section
        "dad", "daily", "dam", "damage", "damages", "damp", "dance", "danger", "dangerous", "dare",
        "dark", "data", "date", "daughter", "dawn", "day", "dead", "deaf", "deal", "dear", "dearth",
        "death", "death sentence", "debate", "debt", "decade", "decay", "decide", "decision",
        "decisive", "declare", "decline", "decongestant", "decorate", "decoration", "decorative",
        "decrease", "deep", "defeat", "defend", "defendant", "defense", "deference", "defiance",
        "deficit", "define", "definite", "definition", "deforestation", "degree", "delay",
        "deliberate", "delicate", "delicious", "delight", "deliver", "demand", "democracy",
        "demonstrate", "dental hygienist", "dentist", "deny", "department", "departure", "depend",
        "dependence", "deplete", "deposit", "depress", "depression", "depth", "derive", "describe",
        "description", "desert", "deserve", "design", "designer", "desire", "desk", "desperate",
        "despite", "destroy", "destruction", "detail", "determine", "determined", "develop",
        "developer", "development", "device", "devote", "diamond", "diarrhea", "diary",
        "dictionary", "didactic", "die", "diet", "dietician", "difference", "different",
        "difficult", "difficulty", "diffident", "dig", "dimension", "dinner", "dip", "direct",
        "direction", "director", "dirt", "dirty", "disagree", "disagreement", "disappear",
        "disappoint", "disappointment", "disapproval", "disapprove", "disaster", "disc",
        "discipline", "disconcert", "discover", "discovery", "discursive", "discuss", "discussion",
        "disease", "disgust", "dish", "dishonest", "dislike", "dismay", "dismiss", "display",
        "disposable", "dispute", "disrespect", "dissolve", "distance", "distant", "distinct",
        "distinguish", "distress", "distribute", "distribution", "district",
        "district attorney", "distrust", "disturb", "dive", "diversity", "divide", "division",
        "divorce", "divulge", "dizzy", "do", "doctor", "document", "dog", "doll", "dollar",
        "domestic", "dominant", "dominate", "domineering", "door", "dorm", "dot", "double", "doubt",
        "down", "draft", "dribble", "dugout", "dusk", "duty-free",
// E section
        "e-mail", "each", "eager", "ear", "earlier", "earlobe", "early", "earn", "earth", "ease",
        "east", "easy", "easygoing", "eat", "ecology", "economic", "economics", "economist",
        "economy", "ecosystem", "edge", "edict", "edit", "edition", "editor", "educate",
        "education", "effect", "effective", "effete", "efficient", "effort", "egg", "either",
        "elastic", "elbow", "elect", "election", "electric", "electrician", "electricity",
        "electronic", "element", "else", "elsewhere", "embarrass", "embarrassment", "emerge",
        "emergency", "emission", "emotion", "emotional", "emphasis", "emphasize", "empire",
        "employ", "employee", "employer", "employment", "empty", "enable", "encounter", "encourage",
        "end", "endangered", "enemy", "energy", "engage", "engaged", "engine", "engineer",
        "English", "enjoy", "enjoyment", "enormous", "enroll", "ensue", "ensure", "enter",
        "entertain", "entertainment", "enthusiasm", "enthusiastic", "entire", "entrance",
        "entreat", "entry", "envelope", "environment", "environmentalist", "envy", "equal",
        "equipment", "equivalent", "erase", "erosion", "error", "escape", "especially", "essay",
        "essential", "establish", "estate", "estimate", "ethnic", "evaluate", "even", "evening",
        "event", "eventually", "ever", "every", "every day", "everybody", "everyday", "everyone",
        "everything", "everywhere", "evidence", "evident", "evil", "ex", "exact", "exactly",
        "exaggerate", "exam", "examination", "examine", "example", "exceed", "excellent", "except",
        "exception", "excess", "exchange", "excite", "excitement", "exclude", "excuse", "executive",
        "exercise", "expatiate", "exploit", "extinct", "extinction", "extroverted", "eyebrow",
        "eyelash", "eyelid",
// F section
        "fabric", "face", "fact", "factor", "factory", "faculty", "fail", "failure", "faint",
        "fair", "faith", "fake", "fall", "false", "fame", "familiar", "family", "famous", "fan",
        "fancy", "far", "farm", "farmer", "fashion", "fast", "fasten", "fat", "fate", "father",
        "father-in-law", "fatuous", "fault", "favor", "favorite", "fear", "fearful", "feasible",
        "feather", "feature", "federal", "fee", "feed", "feel", "feeling", "fellow", "felon",
        "felony", "female", "fence", "festival", "fever", "few", "fiancé", "fiancée", "fiasco",
        "fiber", "field", "field goal", "fierce", "fight", "figure", "fill", "film", "filmmaker",
        "final", "finally", "finance", "financial", "financial aid", "find", "fine", "finger",
        "finish", "finish line", "fire", "firm", "first", "first aid", "first class", "fiscal",
        "fish", "fisherman", "fit", "fix", "flag", "flame", "flash", "flat", "flavor", "flesh",
        "flexible", "flextime", "flight", "flight attendant", "flight deck", "float", "flood",
        "floor", "flour", "flow", "flower", "flu", "fluctuate", "fluid", "flurries", "fly", "focus",
        "fog", "fold", "football", "footnote", "forearm", "forecast", "forehand", "forehead",
        "forever", "formerly", "fossil fuel", "frank", "fraternity", "fraud", "free throw",
        "frequently", "Friday", "friendly", "frustrate", "frustration", "full-time", "fun", "fund",
        "funny", "furniture", "fury",
// F section
        "gain", "gallon", "game", "gap", "garage", "garbage", "garden", "gas", "gate", "gather",
        "gay", "gear", "gender", "gene", "general", "generally", "generate", "generation",
        "generosity", "generous", "gentle", "gentleman", "genuine", "geography", "geothermal",
        "get", "giant", "gibe", "gift", "girl", "give", "glad", "glass", "glib", "global",
        "global warming", "glory", "glove", "glow", "glue", "go", "goal", "goal line", "goalkeeper",
        "goalpost", "god", "gold", "golden", "good", "goodbye", "govern", "government", "governor",
        "GPA", "grab", "graceful", "grade", "gradual", "graduate", "grain", "grammar", "grand",
        "grand slam", "grandchild", "granddaughter", "grandfather", "grandmother", "grandparent",
        "grandson", "grant", "grass", "grateful", "grave", "gravity", "gray", "great", "greed",
        "greedy", "green", "greenhouse effect", "greet", "gregarious", "grief", "grind", "grocery",
        "groom", "groove", "ground", "groundwater", "group", "grow", "guarantee", "guard",
        "guardian", "guess", "guest", "guide", "guilt", "guilty", "gullible", "gum", "gun", "gust",
        "guy",
// F section

    )
}